# [theme]
# base = "dark"
# primaryColor = "#ff4b4b"
# backgroundColor = "#0e1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#fafafa"

[theme]
base = "light"
primaryColor = "#E53935"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
linkColor = "#D32F2F"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#F5F6F8"
secondaryBackgroundColor = "#E5E7EB"
textColor = "#111827"
primaryColor = "#E53935"

[server]
maxUploadSize = 10
headless = true
